-- ALTER TABLE follow
-- ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
-- ADD FOREIGN KEY (follow_user_id) REFERENCES users(id) ON DELETE CASCADE;
-- ADD PRIMARY KEY(user_id,follow_user_id);
ALTER TABLE likes DROP CONSTRAINT IF EXISTS FK_user_id;
ALTER TABLE likes DROP CONSTRAINT IF EXISTS FK_post_id;

ALTER TABLE likes
ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE likes
ADD CONSTRAINT FK_post_id FOREIGN KEY (like_post_id) REFERENCES tweet(id) ON DELETE CASCADE;

ALTER TABLE shares DROP CONSTRAINT IF EXISTS FK_user_id;
ALTER TABLE shares DROP CONSTRAINT IF EXISTS FK_post_id;
ALTER TABLE shares
ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE shares
ADD CONSTRAINT FK_post_id FOREIGN KEY (share_post_id) REFERENCES tweet(id) ON DELETE CASCADE;

ALTER TABLE bookmarks DROP CONSTRAINT IF EXISTS FK_user_id;
ALTER TABLE bookmarks DROP CONSTRAINT IF EXISTS FK_tweet_id;
ALTER TABLE bookmarks DROP CONSTRAINT IF EXISTS bookmarks_twit_id_fkey;
ALTER TABLE bookmarks
ADD CONSTRAINT FK_user_id
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE bookmarks
ADD CONSTRAINT FK_tweet_id
FOREIGN KEY (twit_id) REFERENCES tweet(id) ON DELETE CASCADE;
ALTER TABLE bookmarks DROP CONSTRAINT IF EXISTS UC_bookmarks;
ALTER TABLE bookmarks DROP CONSTRAINT IF EXISTS PK_set;
ALTER TABLE bookmarks ADD CONSTRAINT PK_set UNIQUE(id,user_id,twit_id);

